<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

// Mais informações em: https://github.com/chriskacerguis/codeigniter-restserver

use Restserver\Libraries\REST_Controller;

class MY_Controller extends REST_Controller {
    protected $cors = true;
    protected $json = true;

    public function __construct()
    {
        parent::__construct();
    }

    public function response($data = NULL, $http_code = NULL)
    {
        return new Response($this);
    }

    public function _response($data = NULL, $http_code = NULL)
    {
        parent::response($data, $http_code); // TODO: Change the autogenerated stub
    }
}

class Response {
    private $base;

    public function __construct(MY_Controller $base)
    {
        $this->base = $base;
    }


    public function success($response = array(), $message = 'Ação Realizada com sucesso', $code = 200){
        $this->base->_response(array(
            'code' => $code,
            'error' => false,
            'error_stack' => null,
            'return' => $response,
            'message' => ($message) ? $message : 'Ação realizada com sucesso!'
        ),$code);
    }

    public function error($code = 500, $message = 'Erro ao realizar ação', $error_stack = null){
        $this->base->_response(array(
            'code' => $code,
            'error' => true,
            'error_stack' => $error_stack,
            'return' => null,
            'message' => ($message) ? $message : 'Erro ao realizar ação'
        ),200);
    }
}